# PROMPT/OUTPUT ARGUMENTS
PROMPT_ARGS = {
    'Bamboogle-Jibberish-Full': (['question', 'fact_1', 'fact_2'],
                                 ['question', 'fact 1', 'fact 2', 'actual deduced', 'generated deduced', 'pred answer', 'true answer', 'jibberish answer']),
    'Bamboogle-Full': (['question', 'fact_1', 'fact_2'],
                       ['question', 'fact 1', 'fact 2', 'actual deduced', 'generated deduced', 'pred answer', 'true answer']),
    'Bamboogle-QA': (['question'],
                     ['question', 'pred answer', 'true answer']),
    'Bamboogle-QA (step-by-step)': (['question'],
                     ['question', 'pred answer', 'true answer']),
    'Bamboogle-QAF': (['question', 'fact_1', 'fact_2'],
                      ['question', 'fact 1', 'fact 2', 'pred answer', 'true answer']),
    'Bamboogle-QAF (fact 2 only)': (['question', 'fact_2'],
                                    ['question', 'fact 2','pred answer', 'true answer']),
    'Bamboogle-QAF (fact 1 only)': (['question', 'fact_1'],
                                    ['question', 'fact 1', 'pred answer', 'true answer']),
    'QASC-QA (step-by-step + facts & deductions)': (['question', 'answers'],
                                                    ['question', 'answers', 'generated deduced', 'actual deduced', 'pred answer', 'true answer']),
    'QASC-QA (step-by-step)': (['question', 'answers'],
                               ['question', 'answers', 'generated deduced', 'actual deduced', 'pred answer', 'true answer']),
    'QASC-QA': (['question', 'answers'], 
                ['question', 'answers', 'pred answer', 'true answer']),
    'QASC-QAF': (['question', 'answers', 'fact_1', 'fact_2'], 
                 ['question', 'answers', 'fact 1', 'fact 2', 'pred answer', 'true answer']),
    'QASC-QAF (fact 1 only)': (['question', 'answers', 'fact_1'], 
                               ['question', 'answers', 'fact 1', 'pred answer', 'true answer']),
    'QASC-QAF (fact 2 only)': (['question', 'answers', 'fact_2'], 
                               ['question', 'answers', 'fact 2', 'pred answer', 'true answer']),
    'QASC-QAFD': (['question', 'answers', 'fact_1', 'fact_2', 'deduction'], 
                  ['question', 'answers', 'fact 1', 'fact 2', 'actual deduced', 'pred answer', 'true answer']),
    'QASC-Full': (['question', 'answers', 'fact_1', 'fact_2'], 
                  ['question', 'answers', 'fact 1', 'fact 2', 'actual deduced', 'generated deduced', 'pred answer', 'true answer']),
    'QASC-Full (no MC)': (['question', 'fact_1', 'fact_2'], 
                          ['question' , 'fact 1', 'fact 2', 'actual deduced', 'generated deduced', 'pred answer', 'true answer']),
    'QASC-QA (no MC)': (['question'], 
                        ['question', 'answers', 'pred answer', 'true answer']),
}

# Default output dictionary
OUTPUT_DICT = {
    "question": [],
    "answers": [],
    "fact 1": [],
    "fact 2": [],
    "generated deduced": [],
    "actual deduced": [],
    "pred answer": [],
    "true answer": [],
    "jibberish answer": []
}
